
matrix:
  include:
    - os: osx
      before_install:
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install xquartz; fi
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphicsmagick mono wine; fi
      script:
        - npm run desktop -- build-installer --build-meteor --mac --production
        
    - os: linux
      before_install:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3
      script:
        - npm run desktop -- build-installer --build-meteor --linux --production

language: node_js

node_js:
  - "node"

branches:
  only:
    - master 

cache:
  yarn: true
  directories:
    - node_modules

services:
  - mongodb

before_install:
  - curl https://install.meteor.com/ | sh

script:
  - npm test

deploy:
  provider: releases
  api_key: <your api key for github>
  file: 
    - ".desktop-installer/mac/*"
  skip_cleanup: true
  on:
    tags: true