matrix:
  include:      
    - os: linux
      sudo: required
      services: 
        - docker
        - mongodb
      language: node_js
      node_js:
        - "node"
      addons:
        apt:
          packages:
            - icnsutils
            - graphicsmagick
            - snapd
      before_install:
        - curl https://install.meteor.com/ | sh
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3
      script:
        - npm test
        - npm run build-linux

branches:
  only:
    - master

cache:
  directories:
    - .desktop-installer
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

deploy:
  provider: releases
  api_key:
    secure: QAy6AN+BIMV7yntJz9azJLpN11yC4fDHtsjg1Mgaa2oJ3oCake3fB9dvd9akEXaXEmwFbAmlV+E549Tv7/ECKgjY9un+54ySSKFUwtuyGHk3ZKoYh8+XW1O7aNBoNmnd1ci8soXyu5GlkrWD6U36Heth2J7W0YxR/qmFDYZSD3s=
  file_glob: true
  file:
    - .desktop-installer/*.AppImage
    - .desktop-installer/mac/*.dmg
    - .desktop-installer/mac/*.zip
    - .desktop-installer/win/*.exe
    - .desktop-installer/win/*.nupkg
    - .desktop-installer/win-ia32/*.exe
    - .desktop-installer/win-ia32/*.nupkg
  skip_cleanup: true
  on:
    repo: lacymorrow/cinematic
    tags: true
