os:
  - linux
  - osx

language: node_js

node_js:
  - "node"

branches:
  only:
    - master 

cache:
  yarn: true
  directories:
    - node_modules

services:
  - mongodb

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install xquartz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install wine; fi
  - curl https://install.meteor.com/ | sh

script:
  - npm test
  - npm run desktop -- --build-meteor

before_deploy:
  - npm run desktop -- build-installer --build-meteor --all-archs --win --mac --linux --production

deploy:
  provider: releases
  api_key: <your api key for github>
  file: 
    - ".desktop-installer/mac/*"
  skip_cleanup: true
  on:
    tags: true