matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: '12'
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      services: xvfb
      language: generic

  cache:
    directories:
      - node_modules
      - $HOME/.cache/electron
      - $HOME/.cache/electron-builder

  script:
    - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        export DISPLAY=:99.0
        sh -e /etc/init.d/xvfb start
        sleep 3
      fi

      node --version
      npm --version
      npm install
      npm test

  before_cache:
    - rm -rf $HOME/.cache/electron-builder/wine

  notifications:
    email:
      on_success: never
      on_failure: change

  deploy:
    provider: releases
    api_key:
      secure: QAy6AN+BIMV7yntJz9azJLpN11yC4fDHtsjg1Mgaa2oJ3oCake3fB9dvd9akEXaXEmwFbAmlV+E549Tv7/ECKgjY9un+54ySSKFUwtuyGHk3ZKoYh8+XW1O7aNBoNmnd1ci8soXyu5GlkrWD6U36Heth2J7W0YxR/qmFDYZSD3s=
    file_glob: true
    file:
      - .desktop-installer/*.AppImage
      - .desktop-installer/mac/*.dmg
      - .desktop-installer/mac/*.zip
      - .desktop-installer/win/*.exe
      - .desktop-installer/win/*.nupkg
      - .desktop-installer/win-ia32/*.exe
      - .desktop-installer/win-ia32/*.nupkg
    skip_cleanup: true
    on:
      repo: lacymorrow/cinematic
      branch: release
      tags: true

