
matrix:
  include:
    - os: osx
      before_install:
        - curl https://install.meteor.com/ | sh
        - brew install graphicsmagick mono wine
      script:
        - npm test
        - npm run desktop -- build-installer --build-meteor --mac --production

    - os: linux
      before_install:
        - curl https://install.meteor.com/ | sh
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3
      script:
        - npm test
        - npm run desktop -- build-installer --build-meteor --linux --production

language: node_js

node_js:
  - "node"

branches:
  only:
    - master 

cache:
  yarn: true
  directories:
    - node_modules

services:
  - mongodb

deploy:
  provider: releases
  api_key: <your api key for github>
  file: 
    - ".desktop-installer/mac/*"
  skip_cleanup: true
  on:
    tags: true