environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '6'
    - nodejs_version: '4'
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install --global npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
  - @"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
  - choco install meteor
matrix:
  fast_finish: true
build: off
shallow_clone: true
test_script:
  - node --version
  - npm --version
  - npm test
  - npm run build-win
cache:
  - '%APPDATA%\npm-cache'